services:
  youtubelocal:
    restart: unless-stopped
    container_name: youtube_local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 6969:8080
    stdin_open: true
    tty: true
    volumes:
        - ./youtube_local:/localYT/
        - ./settings.txt:/localYT/settings.txt
        - ./data:/localYT/data
